FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY . .

CMD ["python", "-m", "streamlit", "run", ".\main.py", "--server.port", "10501"]